### ISSUE TITLE
CrazyLogin_Flat_2_MySQL Broken Link

### ISSUE THREAD

**Issue by GershonR** [ST-DDT/CrazyLogin#14]
Hi,

I'm trying to access the DL you uploaded for CrazyLogin_Flat_2_MySQL but the dropbox link seems to be broken, do you have another mirror for it?

Thanks

**Comment by ST-DDT** [comment]
Sorry, I now longer actively maintain this plugin/tool. Due a hardware failure, I don't have the sources for that tool anymore to simply recompile it.
You can still convert your database using the plugin itself:
`/crazylogin mode saveType MYSQL`

This can take a while though, if you have many users. 
So you might want to run it in a separate instance.

If you wish to import it faster, you can just use a text editor to convert it into a SQL script.

PS: I'm unable to change the plugin description on bukkit due to an unknown error.
That page asks me to "try again", but that doesn't work either.

**Comment by GershonR** [comment]
That worked thanks!
